#! /bin/bash

###############################################################################
# Git Abbreviations
###############################################################################

alias gs='git status -sb'
alias ga='git add'
alias gd='git diff'
alias gdc='git diff --cached'
alias gmv='git mv'
alias grm='git rm'
alias grc='git rm --cached'
function gc() { git commit -m "$*"; }
# Pretty log.
alias gl="git log --graph --pretty=format:'%C(yellow)%h%Creset %C(green)%G?%\
    Creset%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
alias gpl='git pull'
alias gpu='git push'
alias gbr='git branch -vv'
alias gco='git checkout'
alias gst='git stash'

# Set the cache to timeout after 1 hour (setting is in seconds)
alias gcache="git config --global credential.helper 'cache --timeout=3600'"

###############################################################################
# Colorize
###############################################################################

alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias less='less -XF --RAW-CONTROL-CHARS --LINE-NUMBERS --LONG-PROMPT'

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Default to human readable figures
alias df='df -h'
alias du='du -h'

# make less more friendly for non-text input files, see lesspipe(1)
[ -x "$(command -v lesspipe.sh)" ] && export LESSOPEN="| lesspipe.sh %s"

# Colorize less using pygmentize if installed with lesspipe
# Try `$ pip install Pygments` if it's not
[ -x "$(command -v pygmentize)" ] && export LESSCOLORIZER=pygmentize

# At least colorize man pages
function man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
        LESS_TERMCAP_me=$'\e[0m' \
        LESS_TERMCAP_se=$'\e[0m' \
        LESS_TERMCAP_so=$'\e[01;44;33m' \
        LESS_TERMCAP_ue=$'\e[0m' \
        LESS_TERMCAP_us=$'\e[01;32m' \
        command man "$@"
}

###############################################################################
# Improved Movement
###############################################################################

# Some more ls aliases
alias ll='ls -AhlF'
alias l='ls -CF'
alias cd..='cd ..' # common typo

# Easily move around directories
function cdl() {
    cd "$1" || return
    ls
}
function mkcd() {
    mkdir -p -- "$1"
    cd -P -- "$1" || return
}
function up() {
    for ((i = 1; i <= $1; i++)); do
        cd ..
    done
}

# Better than `which`
alias whence='type -a'

# Avoid mistakes
alias rm='rm -I'
alias cp='cp -i'
alias mv='mv -i'

# Alias various `open` commands as `o`
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias o='open'
elif [[ "$OSTYPE" == "cygwin" ]]; then
    alias o='cygstart'
elif [[ "$OSTYPE" == "msys" ]]; then
    alias o='explorer.exe' # hoping this works
else
    alias o='xdg-open'
fi

# Quick editing and sourcing.
alias bashrc='$VISUAL $HOME/.bashrc; source $HOME/.bashrc'
alias zshrc='$VISUAL $HOME/.zshrc; source $HOME/.zshrc'
alias localrc='$VISUAL $HOME/.terminalrc/local; source $HOME/.terminalrc/local'

# Useful unarchiver!
function extract() {
    if [ -f "$1" ]; then
        case "$1" in
        *.tar.bz2) tar xjf "$1" ;;
        *.tar.gz) tar xzf "$1" ;;
        *.bz2) bunzip2 "$1" ;;
        *.rar) rar x "$1" ;;
        *.gz) gunzip "$1" ;;
        *.tar) tar xf "$1" ;;
        *.tbz2) tar xjf "$1" ;;
        *.tgz) tar xzf "$1" ;;
        *.zip) unzip "$1" ;;
        *.Z) uncompress "$1" ;;
        *) echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
